// <auto-generated />
using System;
using HayatiArac.Modules.Advert.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HayatiArac.Modules.Advert.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdvertDbContext))]
    [Migration("20260208123024_InitialAdvertModule")]
    partial class InitialAdvertModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("adverts")
                .HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HayatiArac.Modules.Advert.Domain.Entities.Advert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Status");

                    b.ToTable("Adverts", "adverts");
                });

            modelBuilder.Entity("HayatiArac.Modules.Advert.Domain.Entities.AdvertImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdvertId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("AdvertImages", "adverts");
                });

            modelBuilder.Entity("HayatiArac.Modules.Advert.Domain.Entities.AdvertOwnerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdvertOwnerInfos", "adverts");
                });

            modelBuilder.Entity("HayatiArac.Modules.Advert.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", "adverts");
                });

            modelBuilder.Entity("HayatiArac.Modules.Advert.Domain.Entities.Advert", b =>
                {
                    b.HasOne("HayatiArac.Modules.Advert.Domain.Entities.Category", "Category")
                        .WithMany("Adverts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HayatiArac.Modules.Advert.Domain.Entities.AdvertOwnerInfo", "OwnerInfo")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("HayatiArac.Modules.Advert.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("AdvertId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("City");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("District");

                            b1.HasKey("AdvertId");

                            b1.ToTable("Adverts", "adverts");

                            b1.WithOwner()
                                .HasForeignKey("AdvertId");
                        });

                    b.OwnsOne("HayatiArac.Modules.Advert.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("AdvertId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Currency");

                            b1.HasKey("AdvertId");

                            b1.ToTable("Adverts", "adverts");

                            b1.WithOwner()
                                .HasForeignKey("AdvertId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("OwnerInfo");

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("HayatiArac.Modules.Advert.Domain.Entities.AdvertImage", b =>
                {
                    b.HasOne("HayatiArac.Modules.Advert.Domain.Entities.Advert", null)
                        .WithMany("Images")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HayatiArac.Modules.Advert.Domain.Entities.Category", b =>
                {
                    b.HasOne("HayatiArac.Modules.Advert.Domain.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("HayatiArac.Modules.Advert.Domain.Entities.Advert", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("HayatiArac.Modules.Advert.Domain.Entities.Category", b =>
                {
                    b.Navigation("Adverts");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
